<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- CAMERA -->
  <joint name="camera_joint" type="fixed">
    <parent link="chassis" />
    <child link="camera_link" />
    <origin xyz="${x_chassis_size/2} 0 ${z_chassis_size/2}" rpy="0 0 0 " />
  </joint>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${x_camera_size} ${y_camera_size} ${z_camera_size}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <box size="${x_camera_size} ${y_camera_size} ${z_camera_size}" />
      </geometry>
    </collision>
    <xacro:inertial_box mass="${camera_mass}" x="${x_camera_size}" y="${y_camera_size}"
      z="${z_camera_size}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>

  <!-- CAMERA(OPTICAL)-->
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link" />
    <child link="camera_link_optical" />
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
  </joint>

  <link name="camera_link_optical"></link>


  <gazebo reference="camera_link">
    <material>Gazebo/Red</material>
    <sensor name="camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>${horizontal_fov}</horizontal_fov>
        <image>
          <format>R8G8B8</format>
          <width>${camera_frame_width}</width>
          <height>${camera_frame_height}</height>
        </image>
        <clip>
          <near>${min_view_range}</near>
          <far>${max_view_range}</far>
        </clip>
      </camera>

      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <frame_name>camera_link_optical</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
