<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="settings/frame_properties.xacro" />
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">

      <xacro:property name="wheel_separation"
        value="${(y_chassis_size/2 + drive_wheel_length/2) * 2}" />

      <!-- Wheel Informations-->
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${(y_chassis_size/2 + drive_wheel_length/2) * 2}</wheel_separation>
      <wheel_diameter>${drive_wheel_radius * 2}</wheel_diameter>

      <!-- Limits -->
      <!-- <max_wheel_torque>0.8825985</max_wheel_torque> -->
      <max_wheel_torque>100</max_wheel_torque>
      <max_accleration>5.0</max_accleration>

      <!-- Outputs -->
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

    </plugin>
  </gazebo>

</robot>
