<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- LASER -->
  <joint name="laser_joint" type="fixed">
    <parent link="chassis" />
    <child link="laser_frame" />
    <origin xyz="0 0 ${9*z_chassis_size/8}" rpy="0 0 0 " />
  </joint>

  <link name="laser_frame">
    <visual>
      <geometry>
        <cylinder radius="${lidar_frame_radius}" length="${lidar_frame_length}" />
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_frame_radius}" length="${lidar_frame_length}" />
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="${lidar_mass}" radius="${lidar_frame_radius}"
      length="${lidar_frame_length}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>


  <gazebo reference="laser_frame">
    <material>Gazebo/Red</material>
    <sensor name="laser" type="ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>${lidar_samples}</samples>
            <resolution>${lidar_resolution}</resolution>
            <min_angle>${lidar_min_angle}</min_angle>
            <max_angle>${lidar_max_angle}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>${lidar_min_range}</min>
          <max>${lidar_max_range}</max>
          <resolution>${lidar_range_resolution}</resolution>
        </range>
      </ray>

      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>laser_frame</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>
