<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- material -->
  <material name="white">
    <color rgba="1 1 1 1" />
  </material>

  <material name="orange">
    <color rgba="1 0.3 0.1 1" />
  </material>

  <material name="blue">
    <color rgba="0.2 0.2 1 1" />
  </material>

  <material name="black">
    <color rgba="0 0 0 1" />
  </material>

  <!-- SIZE -->
  <xacro:property name="x_chassis_size" value="0.5" />
  <xacro:property name="y_chassis_size" value="0.42" />
  <xacro:property name="z_chassis_size" value="0.14" />

  <!-- BASE LINK-->
  <link name="base_link">

  </link>


  <!-- CHASSIS LINK -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis" />
    <origin xyz="-0.1 0 0 " />
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="${x_chassis_size/2} 0 ${z_chassis_size/2}" />
      <geometry>
        <box size="${x_chassis_size} ${y_chassis_size} ${z_chassis_size}" />
      </geometry>
      <material name="white" />
    </visual>
  </link>


</robot>
