<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- BASE LINK-->
  <link name="base_link">
  </link>

  <!-- BASE_FOOTPRINT LINK-->

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link" />
    <child link="base_footprint" />
    <origin xyz="0 0 0" />
  </joint>

  <link name="base_footprint">
  </link>


  <!-- CHASSIS LINK -->
  <joint name="chassis_joint" type="fixed">
    <parent link="base_link" />
    <child link="chassis" />
    <origin xyz="0 0 0 " />
  </joint>

  <link name="chassis">
    <visual>
      <origin xyz="0 0 ${z_chassis_size/2}" />
      <geometry>
        <box size="${x_chassis_size} ${y_chassis_size} ${z_chassis_size}" />
      </geometry>
      <material name="white" />
    </visual>

    <collision>
      <origin xyz="0 0 ${z_chassis_size/2}" />
      <geometry>
        <box size="${x_chassis_size} ${y_chassis_size} ${z_chassis_size}" />
      </geometry>
    </collision>

    <xacro:inertial_box mass="${chassis_mass}" x="${x_chassis_size}" y="${y_chassis_size}"
      z="${z_chassis_size}">
      <origin xyz="0 0 ${z_chassis_size/2}" />
    </xacro:inertial_box>

  </link>


  <!-- HANDLE -->
  <joint name="handle_joint" type="fixed">
    <parent link="chassis" />
    <child link="handle" />
    <origin xyz="${-x_chassis_size/2} 0 0" />
  </joint>

  <link name="handle">
    <visual>
      <origin xyz="0 0 ${z_handle_size/2}" />
      <geometry>
        <box size="${x_handle_size} ${y_handle_size} ${z_handle_size}" />
      </geometry>
      <material name="white" />
    </visual>

    <collision>
      <origin xyz="0 0 ${z_handle_size/2}" />
      <geometry>
        <box size="${x_handle_size} ${y_handle_size} ${z_handle_size}" />
      </geometry>
    </collision>

    <xacro:inertial_box mass="${handle_mass}" x="${x_handle_size}" y="${y_handle_size}"
      z="${z_handle_size}">
      <origin xyz="0 0 0" />
    </xacro:inertial_box>

  </link>

  <!-- LEFT MOTOR -->
  <joint name="left_motor_joint" type="fixed">
    <parent link="base_link" />
    <child link="left_motor" />
    <origin xyz="-${2*x_chassis_size /6} -${y_chassis_size/2} 0"
      rpy="0 0 0" />
    <axis xyz="0 0 -1" />
  </joint>

  <link name="left_motor">
    <visual>
      <geometry>
        <box size="${x_motor_size} ${y_motor_size} ${z_motor_size}" />
      </geometry>
      <material name="blue" />
    </visual>

    <collision>
      <origin xyz="0 0 ${z_motor_size/2}" />
      <geometry>
        <box size="${x_motor_size} ${y_motor_size} ${z_motor_size}" />
      </geometry>
    </collision>

    <xacro:inertial_box mass="${motor_mass}" x="${x_motor_size}" y="${y_motor_size}"
      z="${z_motor_size}">
      <origin xyz="0 0 ${z_motor_size/2}" />
    </xacro:inertial_box>

  </link>


  <!-- LEFT WHEEL -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="left_motor" />
    <child link="left_wheel" />
    <origin xyz="0 ${-y_motor_size} 0"
      rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1" />
  </joint>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${drive_wheel_radius}" length="${drive_wheel_length}" />
      </geometry>
      <material name="blue" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${drive_wheel_radius}" length="${drive_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${drive_wheel_mass}" length="${drive_wheel_length}"
      radius="${drive_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- RIGHT MOTOR -->
  <joint name="right_motor_joint" type="fixed">
    <parent link="base_link" />
    <child link="right_motor" />
    <origin xyz="-${2*x_chassis_size /6} ${y_chassis_size/2} 0"
      rpy="0 0 0" />
    <axis xyz="0 0 -1" />
  </joint>

  <link name="right_motor">
    <visual>
      <geometry>
        <box size="${x_motor_size} ${y_motor_size} ${z_motor_size}" />
      </geometry>
      <material name="blue" />
    </visual>

    <collision>
      <origin xyz="0 0 ${z_motor_size/2}" />
      <geometry>
        <box size="${x_motor_size} ${y_motor_size} ${z_motor_size}" />
      </geometry>
    </collision>

    <xacro:inertial_box mass="${motor_mass}" x="${x_motor_size}" y="${y_motor_size}"
      z="${z_motor_size}">
      <origin xyz="0 0 ${z_motor_size/2}" />
    </xacro:inertial_box>

  </link>


  <!-- RIGHT WHEEL -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="right_motor" />
    <child link="right_wheel" />
    <origin xyz="0 ${y_motor_size} 0"
      rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1" />
  </joint>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${drive_wheel_radius}" length="${drive_wheel_length}" />
      </geometry>
      <material name="blue" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${drive_wheel_radius}" length="${drive_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${drive_wheel_mass}" length="${drive_wheel_length}"
      radius="${drive_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>

  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- FRONT LEFT CASTER WHEELS -->
  <joint name="front_left_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="front_left_caster_wheel" />
    <origin
      xyz="${2*x_chassis_size /6} ${2*y_chassis_size/5} -${drive_wheel_radius - caster_wheel_radius}"
      rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1" />
  </joint>


  <link name="front_left_caster_wheel">
    <visual>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
      <material name="black" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_length}"
      radius="${caster_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>

  </link>

  <gazebo reference="front_left_caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001" />
    <mu2 value="0.001" />
  </gazebo>

  <!-- FRONT RIGHT CASTER WHEELS -->
  <joint name="front_right_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="front_right_caster_wheel" />
    <origin
      xyz="${2*x_chassis_size /6} -${2*y_chassis_size/5} -${drive_wheel_radius - caster_wheel_radius}"
      rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1" />
  </joint>


  <link name="front_right_caster_wheel">
    <visual>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
      <material name="black" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_length}"
      radius="${caster_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>

  </link>

  <gazebo reference="front_right_caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001" />
    <mu2 value="0.001" />
  </gazebo>

  <!-- BACK LEFT CASTER WHEELS -->
  <joint name="back_left_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="back_left_caster_wheel" />
    <origin
      xyz="-${2*x_chassis_size /6} ${2*y_chassis_size/5} -${drive_wheel_radius - caster_wheel_radius}"
      rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1" />
  </joint>


  <link name="back_left_caster_wheel">
    <visual>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
      <material name="black" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_length}"
      radius="${caster_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>

  </link>

  <gazebo reference="back_left_caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001" />
    <mu2 value="0.001" />
  </gazebo>

  <!-- BACK RIGHT CASTER WHEELS -->
  <joint name="back_right_caster_wheel_joint" type="fixed">
    <parent link="base_link" />
    <child link="back_right_caster_wheel" />
    <origin
      xyz="-${2*x_chassis_size /6} -${2*y_chassis_size/5} -${drive_wheel_radius - caster_wheel_radius}"
      rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1" />
  </joint>


  <link name="back_right_caster_wheel">
    <visual>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
      <material name="black" />
    </visual>

    <collision>
      <geometry>
        <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}" />
      </geometry>
    </collision>

    <xacro:inertial_cylinder mass="${caster_wheel_mass}" length="${caster_wheel_length}"
      radius="${caster_wheel_radius}">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_cylinder>

  </link>

  <gazebo reference="back_right_caster_wheel">
    <material>Gazebo/Black</material>
    <mu1 value="0.001" />
    <mu2 value="0.001" />
  </gazebo>
</robot>
